name: Deploy

on:
  push:
    branches:
      - gh-pages-deploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v7

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Build UI
        run: npm run build

      - name: Add SPA fallback
        run: cp build/index.html build/404.html

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
